(define-module (timmy wireplumber)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix build-system meson)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (gnu packages)
  #:use-module (gnu packages base)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages lua)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages tls)
  #:use-module (gnu packages textutils)
  #:use-module (gnu packages web)
  #:use-module (ice-9 match))

(define-public wireplumber-sans-elogind
  (package
    (inherit wireplumber)
    (name "wireplumber-sans-elogind")
    (arguments
     `(#:configure-flags (list "-Dsystem-lua=true" "-Delogind=disabled")))
    (inputs (modify-inputs (package-inputs wireplumber)
                           (delete "elogind")))))
